exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('games').del();
  await knex('games').insert([
    { name: 'Super Mario Bros.', year: 1985, genre_id: 6, platform_id: 1, description: 'The game that started it all.', image: 'https://example.com/smb.jpg' },
    { name: 'The Legend of Zelda', year: 1986, genre_id: 2, platform_id: 1, description: 'An epic adventure begins.', image: 'https://example.com/loz.jpg' },
    { name: 'Super Mario World', year: 1990, genre_id: 6, platform_id: 2, description: 'Mario and Yoshi team up.', image: 'https://example.com/smw.jpg' },
    { name: 'The Legend of Zelda: A Link to the Past', year: 1991, genre_id: 2, platform_id: 2, description: 'A classic 16-bit adventure.', image: 'https://example.com/lttp.jpg' },
    { name: 'The Legend of Zelda: Ocarina of Time', year: 1998, genre_id: 2, platform_id: 3, description: 'The first 3D Zelda game.', image: 'https://example.com/oot.jpg' },
    { name: 'Super Mario 64', year: 1996, genre_id: 6, platform_id: 3, description: 'Mario enters the third dimension.', image: 'https://example.com/sm64.jpg' },
    { name: 'GoldenEye 007', year: 1997, genre_id: 5, platform_id: 3, description: 'The legendary FPS.', image: 'https://example.com/goldeneye.jpg' },
    { name: 'Final Fantasy VII', year: 1997, genre_id: 3, platform_id: 8, description: 'Cloud Strife against Sephiroth.', image: 'https://example.com/ff7.jpg' },
    { name: 'Metal Gear Solid', year: 1998, genre_id: 12, platform_id: 8, description: 'Tactical espionage action.', image: 'https://example.com/mgs.jpg' },
    { name: 'Grand Theft Auto III', year: 2001, genre_id: 1, platform_id: 9, description: 'Open-world chaos in Liberty City.', image: 'https://example.com/gta3.jpg' },
    { name: 'Halo: Combat Evolved', year: 2001, genre_id: 5, platform_id: 13, description: 'The Master Chief begins his journey.', image: 'https://example.com/halo.jpg' },
    { name: 'Metroid Prime', year: 2002, genre_id: 2, platform_id: 4, description: 'Samus Aran in first-person.', image: 'https://example.com/metroid_prime.jpg' },
    { name: 'Wii Sports', year: 2006, genre_id: 8, platform_id: 5, description: 'The game that changed motion gaming.', image: 'https://example.com/wiisports.jpg' },
    { name: 'The Last of Us', year: 2013, genre_id: 1, platform_id: 10, description: 'A post-apocalyptic journey.', image: 'https://example.com/tlou.jpg' },
    { name: 'Grand Theft Auto V', year: 2013, genre_id: 1, platform_id: 11, description: 'Three criminals in Los Santos.', image: 'https://example.com/gtav.jpg' },
    { name: 'The Witcher 3: Wild Hunt', year: 2015, genre_id: 3, platform_id: 17, description: 'Geralt of Rivia search for Ciri.', image: 'https://example.com/witcher3.jpg' },
    { name: 'The Legend of Zelda: Breath of the Wild', year: 2017, genre_id: 2, platform_id: 7, description: 'Explore the vast lands of Hyrule.', image: 'https://example.com/botw.jpg' },
    { name: 'God of War', year: 2018, genre_id: 1, platform_id: 11, description: 'Kratos in Norse mythology.', image: 'https://example.com/gow.jpg' },
    { name: 'Red Dead Redemption 2', year: 2018, genre_id: 1, platform_id: 11, description: 'The end of the outlaw era.', image: 'https://example.com/rdr2.jpg' },
    { name: 'Minecraft', year: 2011, genre_id: 2, platform_id: 17, description: 'Build anything you can imagine.', image: 'https://example.com/minecraft.jpg' },
    { name: 'Dark Souls', year: 2011, genre_id: 3, platform_id: 10, description: 'Prepare to die.', image: 'https://example.com/darksouls.jpg' },
    { name: 'Skyrim', year: 2011, genre_id: 3, platform_id: 17, description: 'The Elder Scrolls V.', image: 'https://example.com/skyrim.jpg' },
    { name: 'Elden Ring', year: 2022, genre_id: 3, platform_id: 12, description: 'Rise, Tarnished.', image: 'https://example.com/eldenring.jpg' },
    { name: 'Baldur\'s Gate 3', year: 2023, genre_id: 3, platform_id: 17, description: 'Gather your party.', image: 'https://example.com/bg3.jpg' },
    { name: 'Half-Life 2', year: 2004, genre_id: 5, platform_id: 17, description: 'Rise and shine, Mr. Freeman.', image: 'https://example.com/hl2.jpg' },
    { name: 'Portal 2', year: 2011, genre_id: 9, platform_id: 17, description: 'The cake is a lie.', image: 'https://example.com/portal2.jpg' },
    { name: 'Doom', year: 1993, genre_id: 5, platform_id: 17, description: 'Rip and tear.', image: 'https://example.com/doom.jpg' },
    { name: 'Tetris', year: 1984, genre_id: 9, platform_id: 17, description: 'The ultimate puzzle game.', image: 'https://example.com/tetris.jpg' },
    { name: 'Pac-Man', year: 1980, genre_id: 1, platform_id: 17, description: 'Waka waka.', image: 'https://example.com/pacman.jpg' },
    { name: 'Resident Evil 4', year: 2005, genre_id: 13, platform_id: 4, description: 'Leon S. Kennedy in Spain.', image: 'https://example.com/re4.jpg' },
    { name: 'Street Fighter II', year: 1991, genre_id: 10, platform_id: 2, description: 'The definitive fighting game.', image: 'https://example.com/sf2.jpg' },
    { name: 'Starcraft', year: 1998, genre_id: 4, platform_id: 17, description: 'Battle in the Koprulu sector.', image: 'https://example.com/starcraft.jpg' },
    { name: 'World of Warcraft', year: 2004, genre_id: 14, platform_id: 17, description: 'Welcome to Azeroth.', image: 'https://example.com/wow.jpg' },
    { name: 'Fortnite', year: 2017, genre_id: 15, platform_id: 17, description: 'Last one standing.', image: 'https://example.com/fortnite.jpg' },
    { name: 'Sonic the Hedgehog', year: 1991, genre_id: 6, platform_id: 18, description: 'Gotta go fast.', image: 'https://example.com/sonic.jpg' },
    { name: 'Pokémon Red/Blue', year: 1996, genre_id: 3, platform_id: 20, description: 'Gotta catch \'em all.', image: 'https://example.com/pokemon.jpg' },
    { name: 'Metal Gear Solid 3: Snake Eater', year: 2004, genre_id: 12, platform_id: 9, description: 'Big Boss is born.', image: 'https://example.com/mgs3.jpg' },
    { name: 'BioShock', year: 2007, genre_id: 5, platform_id: 17, description: 'Would you kindly?', image: 'https://example.com/bioshock.jpg' },
    { name: 'Mass Effect 2', year: 2010, genre_id: 3, platform_id: 14, description: 'Commander Shepard\'s suicide mission.', image: 'https://example.com/me2.jpg' },
    { name: 'Uncharted 2: Among Thieves', year: 2009, genre_id: 1, platform_id: 10, description: 'Nathan Drake in Shambhala.', image: 'https://example.com/uncharted2.jpg' },
    { name: 'Shadow of the Colossus', year: 2005, genre_id: 2, platform_id: 9, description: 'Behold the giants.', image: 'https://example.com/sotc.jpg' },
    { name: 'Bloodborne', year: 2015, genre_id: 3, platform_id: 11, description: 'Fear the old blood.', image: 'https://example.com/bloodborne.jpg' },
    { name: 'Sekiro: Shadows Die Twice', year: 2019, genre_id: 1, platform_id: 11, description: 'One-armed wolf.', image: 'https://example.com/sekiro.jpg' },
    { name: 'Hollow Knight', year: 2017, genre_id: 6, platform_id: 17, description: 'Descend into Hallownest.', image: 'https://example.com/hollowknight.jpg' },
    { name: 'Chrono Trigger', year: 1995, genre_id: 3, platform_id: 2, description: 'A timeless RPG adventure.', image: 'https://example.com/chronotrigger.jpg' },
    { name: 'Final Fantasy VI', year: 1994, genre_id: 3, platform_id: 2, description: 'The war of the Magi.', image: 'https://example.com/ff6.jpg' },
    { name: 'Castlevania: Symphony of the Night', year: 1997, genre_id: 6, platform_id: 8, description: 'Alucard enters Dracula\'s castle.', image: 'https://example.com/sotn.jpg' },
    { name: 'Silent Hill 2', year: 2001, genre_id: 13, platform_id: 9, description: 'In my restless dreams...', image: 'https://example.com/silenthill2.jpg' },
    { name: 'Diablo II', year: 2000, genre_id: 3, platform_id: 17, description: 'Evil returns.', image: 'https://example.com/diablo2.jpg' },
    { name: 'Counter-Strike', year: 2000, genre_id: 5, platform_id: 17, description: 'Terrorists vs Counter-Terrorists.', image: 'https://example.com/cs.jpg' },
    { name: 'Fallout: New Vegas', year: 2010, genre_id: 3, platform_id: 17, description: 'The Mojave Wasteland.', image: 'https://example.com/fnv.jpg' }
  ]);
};
